### PR TITLE
Implemented GregTech energy adapter for Energy Core multiblock

### PR DESCRIPTION
**Pull request by OneEyeMaker**
### Summary
* Implemented GregTech energy adapter for Energy Core multiblock.
Now this structure can be charged and discharged using GT EU. *Attention*: EU/RF conversion is *lossy* (I used constants `mRFtoEU` and `mEUtoRF` from `GregTech_API`).
This implementation is optional - no hard dependency on GregTech.
* Removed unnecessary block updates where possible (now TileEntities update block and it's neighbors without including neighbors of neighbors).
* Removed some code duplicates.
* Added tooltips for Energy Core multiblock with information about amount of EU that can be extracted.

### Questions for reviewers
* Is there more suitable interface than `IBasicEnergyContainer` for searching candidates for receiving energy from core? `IEnergyConnected` is definitely not sufficient, because one doesn't provide information about voltage and amperage of receiver. And I don't want to send blindly as much energy as possible (and so explode machines).
* Are there some edge cases in calculation of amount of transferred (GT EU) energy?

### CODE REVIEW

**Comment by Dream-Master** [comment]
@OneEyeMaker is this a replacement for <https://github.com/GTNewHorizons/Draconic-Evolution/pull/37> ?

**Comment by OneEyeMaker** [comment]
Yes, this PR is a replacement for #37 .

Looks like author of #37 attempts to replace RF energy API with GT one (which will break existing multiblocks' logic and make GregTech a hard dependency). And that implementation is not complete (look at comments in code of #37 ).

My version implements GT energy adapter without breaking of existing API and is completely *optional*.

**Comment by chochem** [comment]
- RF to EU is a big no in my opinion
- you need to add a lot of details regarding balancing and goals

**Comment by Dream-Master** [comment]
The DE core is very late game so i guess its no issue with RF to EU anymore?

**Comment by chochem** [comment]
I dont know, there is no info whatsoever here. If it allows RF to EU then this needs details not just on power storage balance but also power production balance on top!

**Comment by minecraft7771** [comment]
> The DE core is very late game so i guess its no issue with RF to EU anymore?

Since it's not possibly currently I think no one really has an idea how possibly broken power generation could end up.

**Comment by BlueWeabo** [comment]
I really hope this doesn't convert RF to EU or one will be able to make infinite power. We should make it only transport EU to EU with gt5u installed. And not allow RF to EU. (This is because the EIO creative capacitor exists  and is craftable)

**Comment by boubou19** [comment]
> The DE core is very late game so i guess its no issue with RF to EU anymore?

Except you forget the chaotic capacitor is a thing, which is infinite RFs. So i'm heavily against allowing RF -> EU conversion.

**Comment by OneEyeMaker** [comment]
Original goal was to make such end-game energy storage fully compatible with EU. But I didn't take into account that infinite energy sources are the thing.

Currently I see 2 ways to solve problem with infinite RF energy sources:
* Either disable RF -> EU energy conversion completely (and make GT energy adapter one-directional),
* Or limit EU output to much lower tier than one at which infinite energy sources become available (for example, allowing to output IV or even lower voltage).

**Comment by Dream-Master** [comment]
Did the de stuff output now eu or rf? After your change i mean.

**Comment by chochem** [comment]
> Original goal was to make such end-game energy storage fully compatible with EU.

that is pretty vague. what tiers? what capacity? how does it compare to LSC in cost and capacity?

**Comment by OneEyeMaker** [comment]
I don't intend to create *EU* storage from Energy Core, especially an alternative to LSC. With current implementation Energy Core is inefficient storage for *EU* because conversion is lossy. Energy Core will produce only 72% of EU received (i. e. in chain `EU source -> Energy Core -> EU target` EU target receives 72% energy of EU source).

Currently energy throughput of multiblock isn't limited.  And I need your advice how to balance one:
* Completely disable RF -> EU conversion, only allowing charging using EU.
* Limit EU throughput of multiblock and bind it to specific tiers. Throughput should be noticeable lower than LSC's one to explicitly note that Energy Core is not an alternative to LSC and to prevent issue with infinite RF storages.

**Comment by OneEyeMaker** [comment]
@chochem Any thoughts?

**Comment by chochem** [comment]
there was a short convo on discord you probably missed. according to gdc the chaotic capacitor is output limitted by 500k RF/t and also its UMV now, so nothing that should concern this. (maybe check that)

If its that bad for EU then I guess balance is a much smaller question on the storage side too.

when can you make the energy core? I assume it needs DE cores so UHV?

**Comment by chochem** [comment]
if you want to allow RF->EU you should also look around if there are any other very high RF sources outside of the chaotic capacitor and how they are balanced. We just ignored them in the last few years of dev.

**Comment by OneEyeMaker** [comment]
I close this PR as unnecessary feature. I'll publish another one containing code cleanup and fixes.

**Pull request closed without merging**
