### PR TITLE
Energy core eu

### PR DESCRIPTION
**Pull request by Elisis**

### CODE REVIEW

**Comment by Dream-Master** [comment]
cool idea but check the conflicts

**Comment by Elisis** [comment]
> cool idea but check the conflicts

I know, was just trying to somehow pull over the buildscript changes. I'm doing it manually now

**Comment by Pilzinsel64** [comment]
Any change we can get GregTech as optional depency only and fall-back to RF if GregTech is not installed?

I'm willing to help but I'm not sure what the best solution would be as I haven't had much experience with minecraft modding yet.

**Review by Pilzinsel64 — COMMENTED** [review]
Any change we can get GregTech as optional depency only and fall-back to RF if GregTech is not installed?

I'm willing to help but I'm not sure what the best solution would be as I haven't had much experience with minecraft modding yet.

**Comment by glowredman** [comment]
> Any change we can get GregTech as optional depency only and fall-back to RF if GregTech is not installed?
> 
> I'm willing to help but I'm not sure what the best solution would be as I haven't had much experience with minecraft modding yet.

I agree. DE was usable outside of NH and it would be nice to keep it that way. I too would be willing to assist in keeping compat.

**Comment by miozune** [comment]
Closing as PR 38 got closed

**Pull request closed without merging**
