### PR TITLE
Limit max amount of stacks that can be attracted by magnet at the same time

### PR DESCRIPTION
**Pull request by xchgeax**
Large amounts of items that gets teleported around can cause both client and server lag, and obviously you don't need to attract 5M items to yourself at the same time.

### CODE REVIEW

**Comment by GTNHAfx237v7** [comment]
Finally someone addressed this! Big thanks!

**Review by Dream-Master — APPROVED** [review]

**Comment by boubou19** [comment]
well this will set with a high amount of stacks on the officials, as it's super handy to clean leaking farms

**Comment by xchgeax** [comment]
> well this will set with a high amount of stacks on the officials, as it's super handy to clean leaking farms

you mean get them voided in creative mod? If so it will work with any amount of stacks

**Comment by boubou19** [comment]
More like i use it in survival near a source of lava or if i want to save them all for the player.

**Comment by xchgeax** [comment]
> More like i use it in survival near a source of lava or if i want to save them all for the player.

Well even if you set it to a thousand stacks it still will be better than if it was trying to attract a couple of millions from the drawer you just broke :)

**Pull request merged**
